variable "account_id" {}
variable "db_user" {}
variable "db_password" {}
variable "db_endpoint" {}
variable "db_database" {}
variable "vpc_subnet_1a" {}
variable "vpc_subnet_1c" {}
variable "ecs_front_security_group" {}
variable "ecs_back_security_group" {}