version: '3.8'

services:
  backend:
    container_name: single-tournament-backend
    build:
      context: ./backend
    ports:
      - 8080:8080

  frontend:
    container_name: single-tournament-frontend
    build:
      context: ./frontend
    ports:
      - '80:80'