version: '3.8'

services:
  backend:
    container_name: single-tournament-backend
    build:
      context: ./backend
    ports:
      - 8080:8080
#    tty: true
#    stdin_open: true
#    command: /bin/sh

  frontend:
    container_name: single-tournament-frontend
    build:
      context: ./frontend
    ports:
      - '80:80'
#    tty: true
#    stdin_open: true
#    command: /bin/sh