version: '3.8'

services:
  backend:
    container_name: single-tournament-backend
    build:
      context: ./backend
    ports:
      - 80:80
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ENDPOINT: ${MYSQL_ENDPOINT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  frontend:
    container_name: single-tournament-frontend
    build:
      context: ./frontend
    ports:
      - '8080:8080'