version: '3.8'

services:
  backend:
    container_name: single-tournament-backend
    build:
      context: ./backend
    ports:
      - 80:80

  frontend:
    container_name: single-tournament-frontend
    build:
      context: ./frontend
    ports:
      - '8080:8080'