version: '3.8'
services:
  backend:
    build: 
      context: ./backend
    ports:
      - 3000:3000

  frontend:
    build:
      volumes:
        - ./front:/app
      ports:
        - '3002:3002'
      tty: true
      stdin_open: true
      command: npm run serve