variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "aws_account_id" {}
variable "aws_region" {}
variable "aws_ecr_front_repository_name" {}
variable "aws_ecr_front_image_name" {}
variable "aws_ecr_front_repository_uri" {}
variable "aws_ecr_back_repository_name" {}
variable "aws_ecr_back_image_name" {}
variable "aws_ecr_back_repository_uri" {}
variable "aws_db_user" {}
variable "aws_db_password" {}
variable "aws_db_endpoint" {}
variable "aws_db_database" {}
variable "aws_vpc_subnet_1a" {}
variable "aws_vpc_subnet_1c" {}
variable "aws_ecs_front_security_group" {}
variable "aws_ecs_back_security_group" {}