# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/golang:1.15.8
    working_directory: /go/src/github.com/SyadoWCS/single_tournament
    steps:
      - checkout
      - run: go version
      - run: ls
      - run: cd backend
      - run: go run main.go
      - run: go test -v ./...
  build:
    docker:
      - image: circleci/golang:1.15.8
    working_directory: /go/src/github.com/SyadoWCS/single_tournament
    steps:
      - checkout
      - run: cd backend
      - run: go get -v -t -d ./...
      - run: go build

workflows:
  version: 2.1
  test and build:
    jobs:
      - test
      - build